namespace Nightpath.Migrations
{
    using Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;


    internal sealed class Configuration : DbMigrationsConfiguration<Nightpath.DAL.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            AutomaticMigrationDataLossAllowed = true;
        }

        protected override void Seed(Nightpath.DAL.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            //
            var Districts = new List<District>
            {
                new District {ID=1,DistrictName="Aveiro"},
                new District {ID=2,DistrictName="Beja"},
                new District {ID=3,DistrictName="Braga"},
                new District {ID=4,DistrictName="Bragança"},
                new District {ID=5,DistrictName="Castelo Branco"},
                new District {ID=6,DistrictName="Coimbra"},
                new District {ID=7,DistrictName="Évora"},
                new District {ID=8,DistrictName="Faro"},
                new District {ID=9,DistrictName="Guarda"},
                new District {ID=10,DistrictName="Leiria"},
                new District {ID=11,DistrictName="Lisboa"},
                new District {ID=12,DistrictName="Portalegre"},
                new District {ID=13,DistrictName="Porto"},
                new District {ID=14,DistrictName="Santarém"},
                new District {ID=15,DistrictName="Setúbal"},
                new District {ID=16,DistrictName="Viana do Castelo"},
                new District {ID=17,DistrictName="Vila Real"},
                new District {ID=18,DistrictName="Viseu"},
                new District {ID=19,DistrictName="Ilha da Madeira"},
                new District {ID=20,DistrictName="Ilha de Porto Santo"},
                new District {ID=21,DistrictName="Ilha de Santa Maria"},
                new District {ID=22,DistrictName="Ilha de São Miguel"},
                new District {ID=23,DistrictName="Ilha Terceira"},
                new District {ID=24,DistrictName="Ilha da Graciosa"},
                new District {ID=25,DistrictName="Ilha de São Jorge"},
                new District {ID=26,DistrictName="Ilha do Pico"},
                new District {ID=27,DistrictName="Ilha do Faial"},
                new District {ID=28,DistrictName="Ilha das Flores"},
                new District {ID=29,DistrictName="Ilha do Corvo"}

            };
            Districts.ForEach(s => context.Districts.AddOrUpdate(p => p.DistrictName, s));
            context.SaveChanges();


            var Regions = new List<Region>
            {

                new Region {DistrictID=1,ID=1,RegionName="Águeda"},
                new Region {DistrictID=1,ID=2,RegionName="Albergaria-a-Velha"},
                new Region {DistrictID=1,ID=3,RegionName="Anadia"},
                new Region {DistrictID=1,ID=4,RegionName="Arouca"},
                new Region {DistrictID=1,ID=5,RegionName="Aveiro"},
                new Region {DistrictID=1,ID=6,RegionName="Castelo de Paiva"},
                new Region {DistrictID=1,ID=7,RegionName="Espinho"},
                new Region {DistrictID=1,ID=8,RegionName="Estarreja"},
                new Region {DistrictID=1,ID=9,RegionName="Santa Maria da Feira"},
                new Region {DistrictID=1,ID=10,RegionName="Ílhavo"},
                new Region {DistrictID=1,ID=11,RegionName="Mealhada"},
                new Region {DistrictID=1,ID=12,RegionName="Murtosa"},
                new Region {DistrictID=1,ID=13,RegionName="Oliveira de Azeméis"},
                new Region {DistrictID=1,ID=14,RegionName="Oliveira do Bairro"},
                new Region {DistrictID=1,ID=15,RegionName="Ovar"},
                new Region {DistrictID=1,ID=16,RegionName="São João da Madeira"},
                new Region {DistrictID=1,ID=17,RegionName="Sever do Vouga"},
                new Region {DistrictID=1,ID=18,RegionName="Vagos"},
                new Region {DistrictID=1,ID=19,RegionName="Vale de Cambra"},
                new Region {DistrictID=2,ID=20,RegionName="Castro Verde"},
                new Region {DistrictID=2,ID=21,RegionName="Cuba"},
                new Region {DistrictID=2,ID=22,RegionName="Ferreira do Alentejo"},
                new Region {DistrictID=2,ID=23,RegionName="Mértola"},
                new Region {DistrictID=2,ID=24,RegionName="Moura"},
                new Region {DistrictID=2,ID=25,RegionName="Odemira"},
                new Region {DistrictID=2,ID=26,RegionName="Ourique"},
                new Region {DistrictID=2,ID=27,RegionName="Serpa"},
                new Region {DistrictID=2,ID=28,RegionName="Vidigueira"},
                new Region {DistrictID=2,ID=29,RegionName="Aljustrel"},
                new Region {DistrictID=2,ID=30,RegionName="Almodôvar"},
                new Region {DistrictID=2,ID=31,RegionName="Alvito"},
                new Region {DistrictID=2,ID=32,RegionName="Barrancos"},
                new Region {DistrictID=2,ID=33,RegionName="Beja"},
                new Region {DistrictID=3,ID=34,RegionName="Esposende"},
                new Region {DistrictID=3,ID=35,RegionName="Fafe"},
                new Region {DistrictID=3,ID=36,RegionName="Guimarães"},
                new Region {DistrictID=3,ID=37,RegionName="Póvoa de Lanhoso"},
                new Region {DistrictID=3,ID=38,RegionName="Terras de Bouro"},
                new Region {DistrictID=3,ID=39,RegionName="Vieira do Minho"},
                new Region {DistrictID=3,ID=40,RegionName="Vila Nova de Famalicão"},
                new Region {DistrictID=3,ID=41,RegionName="Vila Verde"},
                new Region {DistrictID=3,ID=42,RegionName="Vizela"},
                new Region {DistrictID=3,ID=43,RegionName="Amares"},
                new Region {DistrictID=3,ID=44,RegionName="Barcelos"},
                new Region {DistrictID=3,ID=45,RegionName="Braga"},
                new Region {DistrictID=3,ID=46,RegionName="Cabeceiras de Basto"},
                new Region {DistrictID=3,ID=47,RegionName="Celorico de Basto"},
                new Region {DistrictID=4,ID=48,RegionName="Miranda do Douro"},
                new Region {DistrictID=4,ID=49,RegionName="Mirandela"},
                new Region {DistrictID=4,ID=50,RegionName="Mogadouro"},
                new Region {DistrictID=4,ID=51,RegionName="Torre de Moncorvo"},
                new Region {DistrictID=4,ID=52,RegionName="Vila Flor"},
                new Region {DistrictID=4,ID=53,RegionName="Vimioso"},
                new Region {DistrictID=4,ID=54,RegionName="Vinhais"},
                new Region {DistrictID=4,ID=55,RegionName="Alfândega da Fé"},
                new Region {DistrictID=4,ID=56,RegionName="Bragança"},
                new Region {DistrictID=4,ID=57,RegionName="Carrazeda de Ansiães"},
                new Region {DistrictID=4,ID=58,RegionName="Freixo de Espada à Cinta"},
                new Region {DistrictID=4,ID=59,RegionName="Macedo de Cavaleiros"},
                new Region {DistrictID=5,ID=60,RegionName="Oleiros"},
                new Region {DistrictID=5,ID=61,RegionName="Penamacor"},
                new Region {DistrictID=5,ID=62,RegionName="Proença-a-Nova"},
                new Region {DistrictID=5,ID=63,RegionName="Sertã"},
                new Region {DistrictID=5,ID=64,RegionName="Vila de Rei"},
                new Region {DistrictID=5,ID=65,RegionName="Vila Velha de Ródão"},
                new Region {DistrictID=5,ID=66,RegionName="Belmonte"},
                new Region {DistrictID=5,ID=67,RegionName="Castelo Branco"},
                new Region {DistrictID=5,ID=68,RegionName="Covilhã"},
                new Region {DistrictID=5,ID=69,RegionName="Fundão"},
                new Region {DistrictID=5,ID=70,RegionName="Idanha-a-Nova"},
                new Region {DistrictID=6,ID=71,RegionName="Góis"},
                new Region {DistrictID=6,ID=72,RegionName="Lousã"},
                new Region {DistrictID=6,ID=73,RegionName="Mira"},
                new Region {DistrictID=6,ID=74,RegionName="Miranda do Corvo"},
                new Region {DistrictID=6,ID=75,RegionName="Montemor-o-Velho"},
                new Region {DistrictID=6,ID=76,RegionName="Oliveira do Hospital"},
                new Region {DistrictID=6,ID=77,RegionName="Pampilhosa da Serra"},
                new Region {DistrictID=6,ID=78,RegionName="Penacova"},
                new Region {DistrictID=6,ID=79,RegionName="Penela"},
                new Region {DistrictID=6,ID=80,RegionName="Soure"},
                new Region {DistrictID=6,ID=81,RegionName="Tábua"},
                new Region {DistrictID=6,ID=82,RegionName="Vila Nova de Poiares"},
                new Region {DistrictID=6,ID=83,RegionName="Arganil"},
                new Region {DistrictID=6,ID=84,RegionName="Cantanhede"},
                new Region {DistrictID=6,ID=85,RegionName="Coimbra"},
                new Region {DistrictID=6,ID=86,RegionName="Condeixa-a-Nova"},
                new Region {DistrictID=6,ID=87,RegionName="Figueira da Foz"},
                new Region {DistrictID=7,ID=88,RegionName="Montemor-o-Novo"},
                new Region {DistrictID=7,ID=89,RegionName="Mora"},
                new Region {DistrictID=7,ID=90,RegionName="Mourão"},
                new Region {DistrictID=7,ID=91,RegionName="Portel"},
                new Region {DistrictID=7,ID=92,RegionName="Redondo"},
                new Region {DistrictID=7,ID=93,RegionName="Reguengos de Monsaraz"},
                new Region {DistrictID=7,ID=94,RegionName="Vendas Novas"},
                new Region {DistrictID=7,ID=95,RegionName="Viana do Alentejo"},
                new Region {DistrictID=7,ID=96,RegionName="Vila Viçosa"},
                new Region {DistrictID=7,ID=97,RegionName="Alandroal"},
                new Region {DistrictID=7,ID=98,RegionName="Arraiolos"},
                new Region {DistrictID=7,ID=99,RegionName="Borba"},
                new Region {DistrictID=7,ID=100,RegionName="Estremoz"},
                new Region {DistrictID=7,ID=101,RegionName="Évora"},
                new Region {DistrictID=8,ID=102,RegionName="Lagoa (Algarve)"},
                new Region {DistrictID=8,ID=103,RegionName="Lagos"},
                new Region {DistrictID=8,ID=104,RegionName="Loulé"},
                new Region {DistrictID=8,ID=105,RegionName="Monchique"},
                new Region {DistrictID=8,ID=106,RegionName="Olhão"},
                new Region {DistrictID=8,ID=107,RegionName="Portimão"},
                new Region {DistrictID=8,ID=108,RegionName="São Brás de Alportel"},
                new Region {DistrictID=8,ID=109,RegionName="Silves"},
                new Region {DistrictID=8,ID=110,RegionName="Tavira"},
                new Region {DistrictID=8,ID=111,RegionName="Vila do Bispo"},
                new Region {DistrictID=8,ID=112,RegionName="Vila Real de Santo António"},
                new Region {DistrictID=8,ID=113,RegionName="Albufeira"},
                new Region {DistrictID=8,ID=114,RegionName="Alcoutim"},
                new Region {DistrictID=8,ID=115,RegionName="Aljezur"},
                new Region {DistrictID=8,ID=116,RegionName="Castro Marim"},
                new Region {DistrictID=8,ID=117,RegionName="Faro"},
                new Region {DistrictID=9,ID=118,RegionName="Gouveia"},
                new Region {DistrictID=9,ID=119,RegionName="Guarda"},
                new Region {DistrictID=9,ID=120,RegionName="Manteigas"},
                new Region {DistrictID=9,ID=121,RegionName="Meda"},
                new Region {DistrictID=9,ID=122,RegionName="Pinhel"},
                new Region {DistrictID=9,ID=123,RegionName="Sabugal"},
                new Region {DistrictID=9,ID=124,RegionName="Seia"},
                new Region {DistrictID=9,ID=125,RegionName="Trancoso"},
                new Region {DistrictID=9,ID=126,RegionName="Vila Nova de Foz Côa"},
                new Region {DistrictID=9,ID=127,RegionName="Aguiar da Beira"},
                new Region {DistrictID=9,ID=128,RegionName="Almeida"},
                new Region {DistrictID=9,ID=129,RegionName="Celorico da Beira"},
                new Region {DistrictID=9,ID=130,RegionName="Figueira de Castelo Rodrigo"},
                new Region {DistrictID=9,ID=131,RegionName="Fornos de Algodres"},
                new Region {DistrictID=10,ID=132,RegionName="Caldas da Rainha"},
                new Region {DistrictID=10,ID=133,RegionName="Castanheira de Pêra"},
                new Region {DistrictID=10,ID=134,RegionName="Figueiró dos Vinhos"},
                new Region {DistrictID=10,ID=135,RegionName="Leiria"},
                new Region {DistrictID=10,ID=136,RegionName="Marinha Grande"},
                new Region {DistrictID=10,ID=137,RegionName="Nazaré"},
                new Region {DistrictID=10,ID=138,RegionName="Óbidos"},
                new Region {DistrictID=10,ID=139,RegionName="Pedrógão Grande"},
                new Region {DistrictID=10,ID=140,RegionName="Peniche"},
                new Region {DistrictID=10,ID=141,RegionName="Pombal"},
                new Region {DistrictID=10,ID=142,RegionName="Porto de Mós"},
                new Region {DistrictID=10,ID=143,RegionName="Alcobaça"},
                new Region {DistrictID=10,ID=144,RegionName="Alvaiázere"},
                new Region {DistrictID=10,ID=145,RegionName="Ansião"},
                new Region {DistrictID=10,ID=146,RegionName="Batalha"},
                new Region {DistrictID=10,ID=147,RegionName="Bombarral"},
                new Region {DistrictID=11,ID=148,RegionName="Lisboa"},
                new Region {DistrictID=11,ID=149,RegionName="Loures"},
                new Region {DistrictID=11,ID=150,RegionName="Lourinhã"},
                new Region {DistrictID=11,ID=151,RegionName="Mafra"},
                new Region {DistrictID=11,ID=152,RegionName="Oeiras"},
                new Region {DistrictID=11,ID=153,RegionName="Sintra"},
                new Region {DistrictID=11,ID=154,RegionName="Sobral de Monte Agraço"},
                new Region {DistrictID=11,ID=155,RegionName="Torres Vedras"},
                new Region {DistrictID=11,ID=156,RegionName="Vila Franca de Xira"},
                new Region {DistrictID=11,ID=157,RegionName="Amadora"},
                new Region {DistrictID=11,ID=158,RegionName="Odivelas"},
                new Region {DistrictID=11,ID=159,RegionName="Alenquer"},
                new Region {DistrictID=11,ID=160,RegionName="Arruda dos Vinhos"},
                new Region {DistrictID=11,ID=161,RegionName="Azambuja"},
                new Region {DistrictID=11,ID=162,RegionName="Cadaval"},
                new Region {DistrictID=11,ID=163,RegionName="Cascais"},
                new Region {DistrictID=12,ID=164,RegionName="Crato"},
                new Region {DistrictID=12,ID=165,RegionName="Elvas"},
                new Region {DistrictID=12,ID=166,RegionName="Fronteira"},
                new Region {DistrictID=12,ID=167,RegionName="Gavião"},
                new Region {DistrictID=12,ID=168,RegionName="Marvão"},
                new Region {DistrictID=12,ID=169,RegionName="Monforte"},
                new Region {DistrictID=12,ID=170,RegionName="Nisa"},
                new Region {DistrictID=12,ID=171,RegionName="Ponte de Sor"},
                new Region {DistrictID=12,ID=172,RegionName="Portalegre"},
                new Region {DistrictID=12,ID=173,RegionName="Sousel"},
                new Region {DistrictID=12,ID=174,RegionName="Alter do Chão"},
                new Region {DistrictID=12,ID=175,RegionName="Arronches"},
                new Region {DistrictID=12,ID=176,RegionName="Avis"},
                new Region {DistrictID=12,ID=177,RegionName="Campo Maior"},
                new Region {DistrictID=12,ID=178,RegionName="Castelo de Vide"},
                new Region {DistrictID=13,ID=179,RegionName="Maia"},
                new Region {DistrictID=13,ID=180,RegionName="Marco de Canaveses"},
                new Region {DistrictID=13,ID=181,RegionName="Matosinhos"},
                new Region {DistrictID=13,ID=182,RegionName="Paços de Ferreira"},
                new Region {DistrictID=13,ID=183,RegionName="Paredes"},
                new Region {DistrictID=13,ID=184,RegionName="Penafiel"},
                new Region {DistrictID=13,ID=185,RegionName="Porto"},
                new Region {DistrictID=13,ID=186,RegionName="Póvoa de Varzim"},
                new Region {DistrictID=13,ID=187,RegionName="Santo Tirso"},
                new Region {DistrictID=13,ID=188,RegionName="Valongo"},
                new Region {DistrictID=13,ID=189,RegionName="Vila do Conde"},
                new Region {DistrictID=13,ID=190,RegionName="Vila Nova de Gaia"},
                new Region {DistrictID=13,ID=191,RegionName="Trofa"},
                new Region {DistrictID=13,ID=192,RegionName="Amarante"},
                new Region {DistrictID=13,ID=193,RegionName="Baião"},
                new Region {DistrictID=13,ID=194,RegionName="Felgueiras"},
                new Region {DistrictID=13,ID=195,RegionName="Gondomar"},
                new Region {DistrictID=13,ID=196,RegionName="Lousada"},
                new Region {DistrictID=14,ID=197,RegionName="Cartaxo"},
                new Region {DistrictID=14,ID=198,RegionName="Chamusca"},
                new Region {DistrictID=14,ID=199,RegionName="Constância"},
                new Region {DistrictID=14,ID=200,RegionName="Coruche"},
                new Region {DistrictID=14,ID=201,RegionName="Entroncamento"},
                new Region {DistrictID=14,ID=202,RegionName="Ferreira do Zêzere"},
                new Region {DistrictID=14,ID=203,RegionName="Golegã"},
                new Region {DistrictID=14,ID=204,RegionName="Mação"},
                new Region {DistrictID=14,ID=205,RegionName="Rio Maior"},
                new Region {DistrictID=14,ID=206,RegionName="Salvaterra de Magos"},
                new Region {DistrictID=14,ID=207,RegionName="Santarém"},
                new Region {DistrictID=14,ID=208,RegionName="Sardoal"},
                new Region {DistrictID=14,ID=209,RegionName="Tomar"},
                new Region {DistrictID=14,ID=210,RegionName="Torres Novas"},
                new Region {DistrictID=14,ID=211,RegionName="Vila Nova da Barquinha"},
                new Region {DistrictID=14,ID=212,RegionName="Ourém"},
                new Region {DistrictID=14,ID=213,RegionName="Abrantes"},
                new Region {DistrictID=14,ID=214,RegionName="Alcanena"},
                new Region {DistrictID=14,ID=215,RegionName="Almeirim"},
                new Region {DistrictID=14,ID=216,RegionName="Alpiarça"},
                new Region {DistrictID=14,ID=217,RegionName="Benavente"},
                new Region {DistrictID=15,ID=218,RegionName="Moita"},
                new Region {DistrictID=15,ID=219,RegionName="Montijo"},
                new Region {DistrictID=15,ID=220,RegionName="Palmela"},
                new Region {DistrictID=15,ID=221,RegionName="Santiago do Cacém"},
                new Region {DistrictID=15,ID=222,RegionName="Seixal"},
                new Region {DistrictID=15,ID=223,RegionName="Sesimbra"},
                new Region {DistrictID=15,ID=224,RegionName="Setúbal"},
                new Region {DistrictID=15,ID=225,RegionName="Sines"},
                new Region {DistrictID=15,ID=226,RegionName="Alcácer do Sal"},
                new Region {DistrictID=15,ID=227,RegionName="Alcochete"},
                new Region {DistrictID=15,ID=228,RegionName="Almada"},
                new Region {DistrictID=15,ID=229,RegionName="Barreiro"},
                new Region {DistrictID=15,ID=230,RegionName="Grândola"},
                new Region {DistrictID=16,ID=231,RegionName="Ponte da Barca"},
                new Region {DistrictID=16,ID=232,RegionName="Ponte de Lima"},
                new Region {DistrictID=16,ID=233,RegionName="Valença"},
                new Region {DistrictID=16,ID=234,RegionName="Viana do Castelo"},
                new Region {DistrictID=16,ID=235,RegionName="Vila Nova de Cerveira"},
                new Region {DistrictID=16,ID=236,RegionName="Arcos de Valdevez"},
                new Region {DistrictID=16,ID=237,RegionName="Caminha"},
                new Region {DistrictID=16,ID=238,RegionName="Melgaço"},
                new Region {DistrictID=16,ID=239,RegionName="Monção"},
                new Region {DistrictID=16,ID=240,RegionName="Paredes de Coura"},
                new Region {DistrictID=17,ID=241,RegionName="Mondim de Basto"},
                new Region {DistrictID=17,ID=242,RegionName="Montalegre"},
                new Region {DistrictID=17,ID=243,RegionName="Murça"},
                new Region {DistrictID=17,ID=244,RegionName="Peso da Régua"},
                new Region {DistrictID=17,ID=245,RegionName="Ribeira de Pena"},
                new Region {DistrictID=17,ID=246,RegionName="Sabrosa"},
                new Region {DistrictID=17,ID=247,RegionName="Santa Marta de Penaguião"},
                new Region {DistrictID=17,ID=248,RegionName="Valpaços"},
                new Region {DistrictID=17,ID=249,RegionName="Vila Pouca de Aguiar"},
                new Region {DistrictID=17,ID=250,RegionName="Vila Real"},
                new Region {DistrictID=17,ID=251,RegionName="Alijó"},
                new Region {DistrictID=17,ID=252,RegionName="Boticas"},
                new Region {DistrictID=17,ID=253,RegionName="Chaves"},
                new Region {DistrictID=17,ID=254,RegionName="Mesão Frio"},
                new Region {DistrictID=18,ID=255,RegionName="Lamego"},
                new Region {DistrictID=18,ID=256,RegionName="Mangualde"},
                new Region {DistrictID=18,ID=257,RegionName="Moimenta da Beira"},
                new Region {DistrictID=18,ID=258,RegionName="Mortágua"},
                new Region {DistrictID=18,ID=259,RegionName="Nelas"},
                new Region {DistrictID=18,ID=260,RegionName="Oliveira de Frades"},
                new Region {DistrictID=18,ID=261,RegionName="Penalva do Castelo"},
                new Region {DistrictID=18,ID=262,RegionName="Penedono"},
                new Region {DistrictID=18,ID=263,RegionName="Resende"},
                new Region {DistrictID=18,ID=264,RegionName="Santa Comba Dão"},
                new Region {DistrictID=18,ID=265,RegionName="São João da Pesqueira"},
                new Region {DistrictID=18,ID=266,RegionName="São Pedro do Sul"},
                new Region {DistrictID=18,ID=267,RegionName="Sátão"},
                new Region {DistrictID=18,ID=268,RegionName="Sernancelhe"},
                new Region {DistrictID=18,ID=269,RegionName="Tabuaço"},
                new Region {DistrictID=18,ID=270,RegionName="Tarouca"},
                new Region {DistrictID=18,ID=271,RegionName="Tondela"},
                new Region {DistrictID=18,ID=272,RegionName="Vila Nova de Paiva"},
                new Region {DistrictID=18,ID=273,RegionName="Viseu"},
                new Region {DistrictID=18,ID=274,RegionName="Vouzela"},
                new Region {DistrictID=18,ID=275,RegionName="Armamar"},
                new Region {DistrictID=18,ID=276,RegionName="Carregal do Sal"},
                new Region {DistrictID=18,ID=277,RegionName="Castro Daire"},
                new Region {DistrictID=18,ID=278,RegionName="Cinfães"},
                new Region {DistrictID=19,ID=279,RegionName="ponta do sol"},
                new Region {DistrictID=19,ID=280,RegionName="porto moniz"},
                new Region {DistrictID=19,ID=281,RegionName="ribeira brava"},
                new Region {DistrictID=19,ID=282,RegionName="santa cruz"},
                new Region {DistrictID=19,ID=283,RegionName="santana"},
                new Region {DistrictID=19,ID=284,RegionName="são vicente"},
                new Region {DistrictID=19,ID=285,RegionName="calheta (madeira)"},
                new Region {DistrictID=19,ID=286,RegionName="câmara de lobos"},
                new Region {DistrictID=19,ID=287,RegionName="funchal"},
                new Region {DistrictID=19,ID=288,RegionName="machico"},
                new Region {DistrictID=20,ID=289,RegionName="Porto Santo"},
                new Region {DistrictID=21,ID=290,RegionName="Vila do Porto"},
                new Region {DistrictID=22,ID=291,RegionName="Ribeira Grande"},
                new Region {DistrictID=22,ID=292,RegionName="Vila Franca do Campo"},
                new Region {DistrictID=22,ID=293,RegionName="Lagoa (São Miguel)"},
                new Region {DistrictID=22,ID=294,RegionName="Nordeste"},
                new Region {DistrictID=22,ID=295,RegionName="Ponta Delgada"},
                new Region {DistrictID=22,ID=296,RegionName="Povoação"},
                new Region {DistrictID=23,ID=297,RegionName="Angra do Heroísmo"},
                new Region {DistrictID=23,ID=298,RegionName="Praia da Vitória"},
                new Region {DistrictID=24,ID=299,RegionName="Santa Cruz da Graciosa"},
                new Region {DistrictID=25,ID=300,RegionName="Calheta (São Jorge)"},
                new Region {DistrictID=25,ID=301,RegionName="Velas"},
                new Region {DistrictID=26,ID=302,RegionName="Lajes do Pico"},
                new Region {DistrictID=26,ID=303,RegionName="Madalena"},
                new Region {DistrictID=26,ID=304,RegionName="São Roque do Pico"},
                new Region {DistrictID=27,ID=305,RegionName="Horta"},
                new Region {DistrictID=28,ID=306,RegionName="Lajes das Flores"},
                new Region {DistrictID=28,ID=307,RegionName="Santa Cruz das Flores"},
                new Region {DistrictID=29,ID=308,RegionName="Corvo"}
            };
            Regions.ForEach(s => context.Regions.AddOrUpdate(p => p.RegionName, s));
            context.SaveChanges();

        }
    }
}

